### ISSUE TITLE
"Real Bout Garou Densetsu Special - Dominated Mind (Japan) (Shokai Genteiban)" boots to black screen

### ISSUE THREAD

**Issue by Goldanas** [socram8888/tonyhax#27] opened 2021-03-26 17:00 UTC
Using Tony Hax 1.2.1 on a PS2 SCPH-30001R (NTSC-US), The game in the subject seems to just hang at a black screen. Other games using the same burn method and CD-R media (Sony) seem to boot just fine, but this one doesn't want to go.

If it's just me let me know. Maybe the non-(Shokai Genteiban) [Limited Edition] version works fine, but I'm out of CD-Rs at the moment, so I can't confirm.

**Comment by socram8888** [comment] 2021-03-26 18:19
Alright, will have a look.

**Comment by socram8888** [comment] 2021-03-26 18:28
There seems to be [three different versions](http://redump.org/discs/quicksearch/real-bout-garou-densetsu-special-dominated-mind/). Could you please confirm which is the serial number of your CD?

**Comment by Goldanas** [comment] 2021-03-26 18:38
It's the (Shokai Genteiban) version, as stated originally, but I did double check the serial on the disc just now, and indeed it matched SLPM_86090.

I haven't tested the Taikenban (Demo) or Original version.

**Comment by socram8888** [comment] 2021-03-27 21:02
Aw sorry, renamed the wrong issue.

**Comment by RandomGamerRiven** [comment] 2021-03-29 23:54
Just to confirm I have the real retail version of this two disc limited edition version of Real Bout Garou Densetsu Special - Dominated Mind and I can confirm on the two listed consoles below the game disc runs correctly. On the latest Tonyhax.

Version: Tonyhax 1.2.2 (Crash Bandicoot 2 PAL E)
Product Number: 
SLPM_86090 [Disc 1] Game Disc
SLPM_86091 [Disc 2] SNK Fan Disc

Consoles tested on:
PS1 PAL SCPH-102 BIOS V4.5
PS2 PAL SCPH-39003 BIOS V5.0 03/19/02

Both discs got into game and I was able to play matches fine on the game disc.

**Comment by socram8888** [comment] 2021-04-03 22:49
Since there's been a report that it boots using original media I'm going to close this. That wouldn't happen if tonyhax wasn't working as intended, as even with an original copy the original game would fail to boot for being out of region.

Please ensure your copy is a clean one, for instance by comparing the checksum against known good values from redump.org.

**Closed by socram8888** 2021-04-03 22:49 UTC
Labels: bug
