### ISSUE TITLE
King's Field Still Stuck on 1.4.5

### ISSUE THREAD

**Issue by Sebbo1298** [socram8888/tonyhax#155] opened 2023-11-03 22:22 UTC
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version? Yes
 - Are you using CD-R media, and not CD-RW? Yes
 - Did you copy all the files in the expected format to the memory card? Yes

**tonyhax version**: 1.4.5
**Installation method**: Copied files from USB to MC via PS2 running freeMCboot
**Entry point game**: Tony Hawk's Pro Skater 3 (PAL - SLES-03645)
**Console model**: SCPH-102
**Integrity check**: Yes, it suceeds
**BIOS version**: 4.4 03/24/00 E
**Target game**: King's Field (JP) (English Patched) (Save Fix) (SLPS-00017)

**Bug explanation**:
Game still gets stuck on "starting" as per issue #113 . Every care taken to ensure it's not an issue my end, including trying another disc and burning as slow as I can.

**Comment by alex-free** [comment] 2023-11-03 23:12
Yes this hasn't been fixed in the original tonyhax yet. Tonyhax international has a fix and it works in the latest version, socram8888 has been busy unfortunately and hasn't fixed it yet.

**Comment by socram8888** [comment] 2023-11-03 23:30
Closing as a duplicate of #153.

The reason I have not fixed it is that I want to eventually, when I finally have some free time, partially decompile (for the third time) the original BIOS, see the executables really start (ie if they do use DoExecute or another different system call), and why the executable header needs to be modified when calling via DoExecute.

**Closed by socram8888** 2023-11-03 23:30 UTC
Labels: bug
