### ISSUE TITLE
Donald Duck Quack Attack doesn't Boot

### ISSUE THREAD

**Issue by Asura-Y** [socram8888/tonyhax#78] opened 2021-05-01 19:29 UTC
after disc swapping tonyhax loads game files and then asks to swap disc again.

Used on ps2, version 1.3.2

**Comment by socram8888** [comment] 2021-05-01 20:49
Next time use the issue format. Closing as this looks like a duplicate of #24

**Closed by socram8888** 2021-05-01 20:49 UTC
Labels: bug
