### ISSUE TITLE
Drive Not Unlocking Correctly with 1.2.x   ...  worksforme with 1.3.1

### ISSUE THREAD

**Issue by nkrul** [socram8888/tonyhax#60] opened 2021-04-12 00:17 UTC
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version? - Yes (verified with Crash Bandicoot 3)
 - Are you using CD-R media, and not CD-RW? (Not there yet)
 - Did you copy all the files in the expected format to the memory card? (Yes)

**tonyhax version**: 1.2.2 AND 1.2.3
**Installation method**: uLaunchElf and a PS2. Copied BESLEM-99999TONYHAX 1st, on its own so its it slot 1. No renaming of files.
**Entry point game**:   Tony Hawk's Pro Skater 2  SLES-02908/ANZ
**Console model**: SCPH 7002
**Integrity check**: Passes
**BIOS version**: BIOS: v4.1 12/16/97 E

**Bug explanation**:
THPS 2 - 'create skater' ->
Music doesn't stop, and the 'console' scrolls to 'Drive region: European' and stops.
verified with another memory card,

On screen:
tonyhax v1.2.2 🐬 orca.pet
Integrity check passed
BIOS: v4.1 12/16/97 E
Unlocking CD drive
Drive region: European

tonyhax v1.2.3 🐬 orca.pet
Integrity check passed
BIOS: v4.1 12/16/97 E
Resetting drive
Unlocking drive

The same card worked and verified with Crash Bandicoot 3 after failing for THPS2, on 1.2.2 and 1.2.3

If I boot up THPS2 after pre-booting with Crash3, the drive unlocks (but music keeps playing)

**Comment by nkrul** [comment] 2021-04-12 00:24
Also works with Cool Boarders 4. I can't see anything specific about the THPS saves, and it works with other titles on my console.

**Comment by socram8888** [comment] 2021-04-12 00:26
That's odd - THPS2 is one of the games I've tested and I know very well it works on real hardware, at least on my SCPH-102.

**Comment by nkrul** [comment] 2021-04-12 00:30
Yeah. I still think I must have done something wrong... but it works fine for other games, and I was careful to follow the script *exactly*

**Comment by nkrul** [comment] 2021-04-12 01:04
More testing - no change in symptoms if tonyhax and THPS2 are the only files on the card.

More testing - If I just pop the cd drive open it does work, even though it doesn't say 'Swap CD now'
I pop in an original disc and it continues on. (dive regions, swap cd now, and instantly boots the next disc).
i.e. 'works', but buggy.

The only difference I can tell is that THPS2 keeps playing music whilst the tonyhax spl is loading/running.

**Comment by socram8888** [comment] 2021-04-12 01:58
Just to be sure - you get to see the "Swap CD now" but after having inserted a new disc, or it does not appear at all?

**Comment by Workz777** [comment] 2021-04-12 07:45
@nkrul 

Hiya, maybe you could try this to see if you get any results -> swap the discs immediatedly after the THPS-2 save file has been loaded, close CD lid, then continue as usual -> choose the “CREATE SKATER” menu and press X.

There was a bug like this with Sports Superbike (before Tonyhax v1.2.3) where the music would still continue playing but the console would freeze on the TonyHax screen. 

Before TonyHax v1.2.3 addressed this bug, swapping the disc immediatedly after the save file was loaded, and the screen said "OK" - helped fix that problem. Hope it can help for you, just putting it out there as an idea to try. Fellow user from here "kingknuts" originally found this solution, see #22 for more details.

**Comment by nkrul** [comment] 2021-04-13 00:32
AFTER swapping discs it shows the 'Swap CD now' - briefly and the console scrolls past when it immediately loads the next game.
This does sound a lot like #22 . And it does work, so yeah.
Perhaps an [un]common issues section?
Thanks for the support people.

**Comment by AmuroRayMan** [comment] 2021-04-13 02:37
I wonder if it's only certain models or BIOS that are affected. I can confirm that on a
`SCPH-101 NTSC U/C, BIOS v4.5 05/25/00 A`
Tonyhax loaded via Tony Hawk 2 works well. The music continues to play when tonyhax is loaded, but I've never had an issue getting the program to run (only issues with the TH2 disc itself not loading).

**Comment by Workz777** [comment] 2021-04-13 08:44
@ nkrul

That's great news the 'work-around method'* gave you positive results :)

Yeah, that's how it worked on the bike gateway games (XS Moto, Castrol, Superbike 1/2). Swap the CD after the save file has been loaded (rather than later when asked at the TonyHax screen) then (as you said) it scrolls fast through the whole TonyHax instruction screen and loads (backup) game without any problems.

@socram8888 ...and yet nkrul was using TonyHax v1.2.3 which fixed that bug with XS Moto, Castrol, Superbike 1/2

@AmuroRayMan ...i will aim to write down my PSOne and PS1 BIOS' and message back later to compare with you guys here. Off the top of my head, i think my PS1 is same as nkrul (PAL v4.1 12/16/97) and my PSOne (PAL xx/xx/00) is similar to yours, but will aim to report back here later with actual BIOS.

Ciao for now

**Comment by socram8888** [comment] 2021-04-13 08:50
It's unlikely that it's issue #22 IMHO. That issue was that the disc drive didn't get reset in software and ignored the unlock commands while playing CD audio. The controller thus never acknowledged the commands, and tonyhax just got stuck waiting for the interrupt to happen. The workaround of opening the tray worked because the controller gets automatically reset and goes back to normal data mode. v1.2.3 issues on its own this reset command in software.

In this case you don't even get to see the "Integrity check passed" or the BIOS version message which happens even before any access to the disc drive takes place. And it's even weirder because it's a game I have actually also tested on physical hardware and confirmed to boot just fine.

**Comment by Workz777** [comment] 2021-04-13 09:23
@socram8888 ...it's strange that when nkrul tries #22 -> 'Swapping CD early method' (after gateway save file loaded 'OK') - it works. 

Re: audio playing in the background on the purple / blue screens....

I found in tests, the 'Swapping CD early method' cuts off all (gateway game) audio music playing in the background once the CD lid has been opened, so the purple / blue loading screens have no audio.

However, when TonyHax v1.2.3 fixed the bug for XS Moto, Castrol, Superbike 1/2, the background music (from those gateway games) can still be heard on the "Purple" & "Blue" screens, before TonyHax loads up and boots backup game.

**Comment by Workz777** [comment] 2021-04-16 10:54
Sorry for delay, was away due to work stuff.

Here (if it helps) are the BIOS versions for my PSOne & Fat PS1

PSOne = Bios v4.4 03/24/00 (E)

Fat PS1 = Bios v3.0 01/06/97 (E)

...not quite the same as your BIOS versions (nkrul & AmuroRayMan)

Before TonyHax v1.2.3, both my PS1s had an issue / bug with XS Moto, Superbike 1 & 2, Castrol Racing, similar to your gate-way game problems / symptoms. 

I have ordered THPS-2 from eBay so i can test that gate-way game, will aim to report back results for you guys once game arrives, all being well.

**Comment by socram8888** [comment] 2021-04-16 13:17
Unless I broke something, last time I tried tonyhax on real hardware (v1.2.1 I think it was) it worked just fine on my SCPH-102 (also with BIOS 4.4)

**Comment by nkrul** [comment] 2021-04-21 10:30
**v1.3.1** Works just fine. I'll still clone the repo, just to play around.
Thanks dude <3

**Comment by socram8888** [comment] 2021-04-21 10:35
Perfect! I'll close the issue then.

**Closed by socram8888** 2021-04-21 10:35 UTC
Labels: bug
