### ISSUE TITLE
NTSC games have a greenish color palette on a PAL PS2

### ISSUE THREAD

**Issue by Skosef** [socram8888/tonyhax#159] opened 2024-07-28 11:25 UTC
**Version**: Latest 
**Installation method**: ULaunchElf
**Entry Point Game**: Cool Boarders 4 PAL
**Console model**: SCPH 30004 PS2
**Integrity check**: Passes
**BIOS version**: v5.0 10/04/01 E
**Target game**: Suspected to happen on every NTSC games. Games that have been tested so far: Grand theft auto 2 (SLUS-00789). Mortal Kombat 4 (SLUS-00605). Mortal Kombat Trilogy (SLUS-00330)

**Bug explanation**:

When loading into an NTSC backup game on a PAL PS2 with a PAL entry point game, the loaded game has a sort of green shifted color palette, and the screen is also incorrectly positioned, making it so the top parts of the game aren’t visible. I have confirmed that this issue doesn’t occur when loading into a PAL game, nor does it occur on a PS1.

**Comment by socram8888** [comment] 2024-07-28 12:12
Hello. Thanks for the bug report. I will be closing, though, since it is a duplicate of #25 - the PS2 will not let a PS1 game (at least without some dirty tricks I've not tried to uncover) to change the video mode. Changes to PS1 video mode registers are totally ignored.

**Closed by socram8888** 2024-07-28 12:12 UTC
Labels: bug
