### ISSUE TITLE
Antipiracy screen

### ISSUE THREAD

**Issue by gibran19x** [socram8888/tonyhax#92] opened 2021-06-13 05:48 UTC
**tonyhax version**: tonyhax-v1.4.1
**Game name**: Saru! Get You! (ape escape)
**Game code**: SCPS-10091
**Executable hash**: i don´t know
**Triggered at**: after the tonyhax interface
**Is the console chipped?**: Yes
**Is it an original disc or a burned copy?**: original disc

**Comment by socram8888** [comment] 2021-06-14 09:48
I've had a look and I can't neither reproduce it on my console neither find the antipiracy on the disc files, so I'm not sure if I'll be able to patch it.

**Comment by qkwyx** [comment] 2021-07-03 03:29
@socram8888 I have a gameshark cheat that can bypass, if you want I can share it.

**Comment by socram8888** [comment] 2021-07-03 08:06
@qkwyx that'd be helpful to find the antipiracy code, thanks

**Comment by qkwyx** [comment] 2021-07-03 14:53
Saru! Get You!  (NTSC-J)
D0136A8A 1040
80136A8A 1000

Saru! Get You!  (NTSC-J) (Alternative code)
D0136B00 2021
80136AFC FFF6
D0136B00 2021
80136AFE 1000

Saru! Get You!  Playstation the Best (NTSC-J)
D0136AAA 1040
80136AAA 1000

I tested it on my 5501 with a burned copy same as redump.

**Comment by socram8888** [comment] 2021-07-04 11:32
![photo_2021-07-04_13-31-07](https://user-images.githubusercontent.com/515068/124383319-5fd93e80-dcbb-11eb-96cf-ba3a39ffd752.jpg)

Tried on my SCPH-102 and I cannot replicate it by any means. I've set a breakpoint on no$psx at 80136A88 (the address that code "80136A8A" indicates there's a conditional branch) and I can't still find any way to replicate it.

**Comment by qkwyx** [comment] 2021-07-09 00:54
I thought the cheat codes can help the cause of it. Anyways, nice setup and thanks for your continuous support on Tonyhax.

**Comment by alex-free** [comment] 2022-10-11 02:48
> ![photo_2021-07-04_13-31-07](https://user-images.githubusercontent.com/515068/124383319-5fd93e80-dcbb-11eb-96cf-ba3a39ffd752.jpg)
> 
> Tried on my SCPH-102 and I cannot replicate it by any means. I've set a breakpoint on no$psx at 80136A88 (the address that code "80136A8A" indicates there's a conditional branch) and I can't still find any way to replicate it.
> 
> EDIT: For the record, I am using the v1.0 version, with MD5 of 5c70c89355b58111c1fafd050bdeef49.

I think I figured out why you can't see the address being written to. This game appears to only be using the test commands/SCEX counters to test for 'dumb' modchips. No readTOC is being sent or anything like that.

It also appears that unless this test fails (emulators all seem to pass it) then that address won't be written to. That's my theory anyways, I need to figure out how to emulate a dumb modchip really to confirm this I guess. But the AP code is definitely there if you look at the CD commands being sent immeditely before the 'sony computer entertainment inc presents' screen.

The reason most of the AP games are slipping through the original AP patch of Tonyhax is because there are multiple different versions of the AP module. If you notice it seems to be the earliest games with AP that fail.

- Send GetSCEXcounters (Gen 1, only can detect dumb modchips)
- Send GetSCEXcounters AND readTOC (Gen 2, can detect disc swap/unlock/dumb modchips)

I'm addressing AP in Tonyhax International completely different then what the OG Tonyhax does, so this game will work in the next update. I just figured I'd drop this explanation here ifi anyone finds it useful.

**Comment by socram8888** [comment] 2022-11-25 08:18
Fixed in 3e140b8a9103897442c2adb4eb6dd27a84479344

**Closed by socram8888** 2022-11-25 08:18 UTC
Labels: antipiracy

**Comment by socram8888** [comment] 2022-11-26 00:17
Available in [tonyhax v1.4.4](https://github.com/socram8888/tonyhax/releases/tag/v1.4.4)
