### ISSUE TITLE
Um Jammer Lammy PAL Anti-Piracy screen

### ISSUE THREAD

**Issue by LMS737** [socram8888/tonyhax#100] opened 2021-07-10 23:37 UTC
**tonyhax version**: V1.4.3
**Game name**: Um Jammer Lammy
**Game code**: SCES-017.53
**Executable hash**: MD5 da64abe3270f8ab7ce96d5b3065b0c47
**Triggered at**: After Sony presents and then the anti modchip screen comes up
**Is the console chipped?**: Yes

I am using PAL PS2 3900X and I get the anti piracy screen in Japanese language when using the boot disc method. This game is the PAL version and is a PAL game that uses anti modchip instead of libcrypt protection.

**Comment by socram8888** [comment] 2021-07-11 19:49
Will have to test later on my console but again, as with issue #92, I can neither replicate this issue on no$psx nor find the modchip checking code on the main executable nor using a quick grep on other files.

**Comment by LMS737** [comment] 2021-07-11 20:01
Alright, thanks for looking into it. This game does work on a full stealth PS1 console (without using TonyHax). 

The moment you load this game up on a non stealth console, it should trigger the anti mod screen. I am not sure if this will also trigger by running TonyHax on an unchipped console.

**Comment by socram8888** [comment] 2021-07-11 20:04
The standard anti-modchip payload I had seen so far checked not only for the absence of the wobble on the outer tracks (busting modchips) but also the presence of the wobble in the first ones (detecting swap tricks).

I can't find anywhere the payload for this game so I am not sure.

**Comment by qkwyx** [comment] 2021-07-13 03:53
@socram8888 I have a gameshark cheat but I don't know if it can help you with.

D01DCD59 0002
D01D813B 0092
801D813B 00A2

**Comment by BananaByte23** [comment] 2021-07-25 15:37
The best alternative would be to find the protection fix (in other words a .ppf patch) for a game that doesn't work for you on your system. For example I have a patched spyro 3 disc (the perfect patch) and I play it on my console with tonyhax and it doesn't crash or anything. Iirc there's a protection patch for PAL um jammer lammy so you might to look up for it on google.

**Comment by socram8888** [comment] 2022-11-25 08:18
Fixed in 3e140b8a9103897442c2adb4eb6dd27a84479344

**Closed by socram8888** 2022-11-25 08:18 UTC
Labels: antipiracy

**Comment by socram8888** [comment] 2022-11-26 00:17
Available in [tonyhax v1.4.4](https://github.com/socram8888/tonyhax/releases/tag/v1.4.4)

**Comment by LMS737** [comment] 2022-11-26 02:50
I can confirm it works on the PS2 now with non stealth. Thanks!

**Comment by socram8888** [comment] 2022-11-26 09:58
Thanks! Have you been affected by issue #118? I cannot reproduce it in an emulator and my PS2 is dead so I can't try with real hardware atm

**Comment by LMS737** [comment] 2022-11-26 11:51
I have just played like 15 minutes through the first three stages and I have not experienced any lockups during the multiple loading screens. Everything seems to work fine with my limited playtime.

My boot method is using the boot-cd + Matrix Infinity modchip on PS2.

Maybe he needs to specify when and where exactly it happens, which loading screen exactly. Because maybe it happens hours later? I don't know. Or maybe because he was not using the latest v1.4.4 version.

The difference I spot is that he uses the USA version, a different entry point and also an older Tony Hax version. I recommend him trying with the latest and check if that has resolved it.

Hope that helps you!

**Comment by socram8888** [comment] 2022-11-26 12:14
Thanks, @LMS737 ! Will ask him for more details. It could've gotten magically fixed somehow in one of the many reworks I did in the BIOS reinitialization.
