### ISSUE TITLE
Ghost in the Shell does not boot

### ISSUE THREAD

**Issue by AbdomenFella** [socram8888/tonyhax#47] opened 2021-04-07 08:04 UTC
tonyhax ver 1.2.2
installed through ulaunchelf on PS2
Tony Hawk's Pro Skater 3 NTSC-U
Playstation 2 3900X
stuck at tonyhax screen
Ghost in the Shell SLUS-00552

**Comment by socram8888** [comment] 2021-04-07 08:10
What do you mean stuck? It does not recognize the disc? It does not detect the tray is getting opened and closed?

**Comment by Workz777** [comment] 2021-04-07 13:55
@AbdomenFella 

Maybe try this and see if you get any results... 

Using your Tony Hawk's Pro Skater 3 NTSC-U

(1) Boot the game as you’d normally do.
(2) On the main menu, wait until the save file is automatically loaded.
**(3) Once done -> Swap CD Now - Shut Lid**
(4) Choose the “CREATE SKATER” menu and press X.
(5) After a couple seconds, TonyHax should boot and run game.

So basically, instead of swapping CDs on the TonyHax screen (when asked), do it right after the save game file has loaded then continue the steps as usual.

Please let me know if this helped any, it was helping some of the racing games (Castrol, Superbike, XS Moto) on the 'gate way' games list, which were getting stuck on the TonyHax screen. But then TonyHax v1.2.3 has since fixed those games that had that bug.

**Comment by Goldanas** [comment] 2021-04-08 21:33
![IMG_20210408_142536](https://user-images.githubusercontent.com/67668858/114098819-c1ce0780-9876-11eb-80a1-94e18d23500b.jpg)
I believe he means what he sees here in the attached screenshot. It seems to get stuck at "Starting", which I haven't seen with other games (just getting stuck at a black screen after this with RB Dominated Mind and the English Patch of Tobal 2).

I'm also using a PS2, though mine is a 30001R. Redump set, confirmed. Entry point is Cool Boarders 4. I tried both the normal method where I wait for it to say swap disc, and also the recommendation above where you put the disc in before tapping the button to initiate the hack.

I wonder if there's maybe an issue with certain titles only on PS2? Curious if a PS1 user would see the same thing.

**Comment by AmuroRayMan** [comment] 2021-04-09 18:42
I can test on PS1 later today, I'll update with how it goes.

**Comment by Goldanas** [comment] 2021-04-10 14:52
Perhaps this is related to #24 ?

**Comment by socram8888** [comment] 2021-04-10 17:15
I'll close this, since @AmuroRayMan indeed confirmed it works on a PS1 and thus is likely the same bug as #24.

**Closed by socram8888** 2021-04-10 17:15 UTC
Labels: bug
