### ISSUE TITLE
Parasite Eve (USA) Fails at Loading Executable

### ISSUE THREAD

**Issue by AmuroRayMan** [socram8888/tonyhax#12] opened 2021-03-23 08:21 UTC
There's no crash but it locks up at the Loading Executable step. I had previously tested both discs on an earlier version and it failed on that step. I updated to 1.2.1 today and tested disc 1 again but the same behavior occurs. 

Output:
```
Drive region: American
...
Loading SYSTEM.CNF
TCB = 00000004
EVENT = 00000016
STACK = 801FFF00
BOOT = cdrom:\SLUS_006.62;1
Configuring kernel
Loading executable
```

I can get my BIOS version if necessary, the system is one of the smaller white psone models though. Most games are working so far for me.

**Comment by socram8888** [comment] 2021-03-24 10:46
What on earth, this game's executable is nuking the entire tonyhax program off the console's RAM for no reason. No wonder it's crashing.

**Comment by socram8888** [comment] 2021-03-24 12:06
This is gonna be hard to solve. The problem is that the game's executable overlaps tonyhax, so when loading the entire program gets wiped. I've tried to make use of a buggy BIOS call with f3f2d72b7e93d4b81f9a9e865ece0a4ecd3c766d. That's the best I can do.

Could you please try it out? The game seems not to want to boot at all on my emulator: 
[tonyhax-commit-f3f2d72b.zip](https://github.com/socram8888/tonyhax/files/6196934/tonyhax-commit-f3f2d72b.zip)

**Comment by AmuroRayMan** [comment] 2021-03-24 20:36
It seems to be working!

For disc 1 the game booted, I sat through the opening, started a new game, sat through that opening and at least got to where you can control the main character with no issues.

I don't have a save for disc 2, but I did try booting the game. It booted successfully and it got to the menu okay, I clicked new game and it told me to put in disc 1. So for as far as I can test disc 2 it seems to be working.

I'll open a new report if disc 2 has issues in the future, but I think the issue is solved for now. Thank you so much! 

Hopefully this method works with games that have a similar problem.

**Comment by socram8888** [comment] 2021-03-24 20:38
Perfect, glad to know it works. Closing.

**Closed by socram8888** 2021-03-24 20:38 UTC
Labels: bug, question
